# Generated by Django 2.1.3 on 2018-11-29 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Phone_Number', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='img',
            field=models.IntegerField(default=0),
        ),
    ]
